#!/bin/bash

start() {
  cd /home/ec2-user/tax-calculation
  forever start dist/index.js
}

stop() {
  uid=$(forever list | grep dist/index.js | awk '{ print $3 }')
  if [ "${uid}" ]
  then
    forever stop ${uid}
  fi
}

status() {
  forever list
}

source /home/ec2-user/.nvm/nvm.sh
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo $"Uso: tax-calculation ( start | stop | restart | status )"
esac
